version: '3.8'

services:
  random_btc:
    build: .
    container_name: random_btc_app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped
